# Generated by Django 4.0.3 on 2022-03-10 03:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True)),
                ('name', models.TextField(max_length=80)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=80)),
                ('first_year_active', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('up_vote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('name', models.TextField(max_length=80)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.albums')),
            ],
            options={
                'db_table': 'lyrics',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.artists'),
        ),
        migrations.AlterUniqueTogether(
            name='albums',
            unique_together={('artist', 'year', 'name')},
        ),
    ]
