# Generated by Django 4.0.3 on 2022-03-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.TextField(max_length=80, unique=True),
        ),
    ]
