# Generated by Django 4.0.3 on 2022-03-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_artists_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lyrics',
            unique_together={('name', 'text')},
        ),
    ]
